SHOW Databases;

CREATE DATABASE webFOCUS;

USE webFOCUS;

SHOW TABLES;

-- CREATING TABLE1
CREATE TABLE TABLE1 (
	EMP_NO INTEGER PRIMARY KEY,
    JOIN_DATE DATE,
    SCH_SEQ_NO_4 INTEGER,
    SHOPFLOOR_BLD_DATE DATE,
    SCHED_TYPE VARCHAR(200)
);


-- CREATING TABLE2
CREATE TABLE TABLE2 (
	EMP_NO INTEGER references TABLE1.EMP_NO,
    VEH_MDL_TYPE_CAB VARCHAR(200),
    SV_TYPE_CD VARCHAR(100)
);

-- Insert into TABLE1
INSERT INTO TABLE1 (EMP_NO, JOIN_DATE, SCH_SEQ_NO_4, SHOPFLOOR_BLD_DATE, SCHED_TYPE) VALUES
	(101, '2022-01-15', 4001, '2022-02-01', 'Regular'),
	(102, '2022-02-20', 4002, '2022-03-05', 'Overtime'),
	(103, '2022-03-25', 4003, '2022-04-10', 'Night Shift'),
	(104, '2022-04-30', 4004, '2022-05-15', 'Weekend'),
	(105, '2022-05-10', 4005, '2022-06-01', 'Holiday');

-- Insert into TABLE2
INSERT INTO TABLE2 (EMP_NO, VEH_MDL_TYPE_CAB, SV_TYPE_CD) VALUES
	(101, 'Sedan', 'SVC01'),
	(102, 'SUV', 'SVC02'),
	(103, 'Hatchback', 'SVC03'),
	(104, 'Truck', 'SVC04'),
	(105, 'Convertible', 'SVC05');


-- PRINTING TABLE 1
SELECT * FROM TABLE1;

-- PRINTING TABLE2
SELECT * FROM TABLE2;

-- JOINING TWO TABLES.
CREATE TABLE TABLE12 AS 
SELECT T1.EMP_NO, JOIN_DATE, SCH_SEQ_NO_4, SHOPFLOOR_BLD_DATE, SCHED_TYPE, VEH_MDL_TYPE_CAB, SV_TYPE_CD 
FROM TABLE1 T1 JOIN TABLE2 T2 
ON T1.EMP_NO = T2.EMP_NO;

DROP TABLE TEMPTABLE1;

-- TABLE TEMPTABLE
CREATE TABLE TEMPTABLE1 AS SELECT VEH_MDL_TYPE_CAB, EMP_NO, JOIN_DATE, SCH_SEQ_NO_4, 
		@CAB := CAB(VEH_MDL_TYPE_CAB) AS CAB,
		TRUCK(EMP_NO, @CAB) AS TRUCK,
        @DATE_A := DATE_A(JOIN_DATE) AS DATE_A,
        @SEQ_A := SEQ_A(SCH_SEQ_NO_4) AS SEQ_A,
        COMBO2(@DATE_A, @SEQ_A) AS COMBO2
FROM TABLE12
WHERE CAST(EMP_NO AS CHAR(100)) <> 'S______' AND SV_TYPE_CD <> 'PL3'
ORDER BY JOIN_DATE, SCH_SEQ_NO_4;

SELECT * FROM TEMPTABLE1;

-- TABLE FIN_TABLE
CREATE TABLE FIN_TABLE AS SELECT EMP_NO, JOIN_DATE, SCH_SEQ_NO_4, (1 + 1) AS TNUM FROM TEMPTABLE1
WHERE COMBO2 >= 0 LIMIT 120;

SELECT * FROM FIN_TABLE;

-- DROP THE FUNCTION 
DROP FUNCTION IF EXISTS COMBO2;

-- GETTING THE FUNCTIONS ACTIVE IN DB
SHOW FUNCTION STATUS WHERE DB = 'WEBFOCUS';

DELIMITER $$
CREATE FUNCTION CAB(VEH_MDL_TYPE_CAB VARCHAR(200))
RETURNS	CHAR(3)
DETERMINISTIC
BEGIN
	DECLARE RESULT VARCHAR(200);
    
    IF VEH_MDL_TYPE_CAB = 'D' THEN
		SET RESULT = 'MIL';
	ELSE
		SET RESULT = VEH_MDL_TYPE_CAB;
	END IF;
    
    RETURN LEFT(RESULT,3);
END$$

DELIMITER $$
CREATE FUNCTION DATE_A(DATE_A DATE)
RETURNS CHAR(8)
DETERMINISTIC
BEGIN
	RETURN DATE_FORMAT(DATE_A, '%Y%m%d');
END$$

DELIMITER $$
CREATE FUNCTION SEQ_A(SCH_SEQ_NO_4 INTEGER)
RETURNS CHAR(5)
DETERMINISTIC
BEGIN
	RETURN LEFT(SCH_SEQ_NO_4, 5);
END$$

DELIMITER $$
CREATE FUNCTION TRUCK(EMP_NO INTEGER, CAB CHAR(3))
RETURNS CHAR(9)
DETERMINISTIC
BEGIN
	RETURN LEFT(CONCAT(EMP_NO, CAB), 9);
END$$


DELIMITER $$
CREATE FUNCTION COMBO2(DATE_A VARCHAR(8), SEQ_A VARCHAR(5))
RETURNS CHAR(13)
DETERMINISTIC
BEGIN
	RETURN LEFT(CONCAT(DATE_A, SEQ_A), 13);
END$$   





    
    
